import = ["/home/younix/.config/alacritty/colors.toml", "/home/younix/.config/alacritty/fonts.toml"]
live_config_reload = true

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control|Shift"

[shell]
program = "/bin/zsh"

[window]
decorations = "full"
dynamic_title = true
opacity = 1.0
startup_mode = "Windowed"

[window.dimensions]
columns = 80
lines = 26

[window.padding]
x = 20
y = 20
