#!/bin/bash

current_info="$HOME/.config/theme-setter/info/current.json"

if [[ $1 == '--mode' ]]; then
    echo $(jq ".mode" "$current_info") | sed 's/\"//g'
elif [[ $1 == '--wallpaper' ]]; then
    echo $(jq ".wallpaper" "$current_info") | sed 's/\"//g'
else
    echo $(jq ".theme" "$current_info") | sed 's/\"//g'
fi